# Generated by Django 2.2.19 on 2022-12-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221214_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='author',
        ),
    ]
