# Generated by Django 4.1.4 on 2023-01-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_author_alter_group_description_alter_group_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
