# Generated by Django 4.1.4 on 2023-01-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_author_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
