# Generated by Django 4.1 on 2023-01-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='body',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_answered',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
